/**
 * home-prose.ts — build-time hygiene for the preserved WordPress home copy.
 *
 * WHY: the home prose is injected VERBATIM from src/fragments/home/body.html
 * (penalty recovery), and that fragment is REGENERATED by the daily WP sync —
 * so hand-editing it is not durable. Anything that must not ship is removed
 * here, at render time, exactly like scrubFirstHandClaims() / ensureSponsored()
 * / stripRetiredBrands() elsewhere in the data layer.
 *
 * Every transform is:
 *   - anchored on stable text in the fragment,
 *   - a NO-OP when its pattern is absent (a WP rewrite can never break the
 *     page — worst case the copy simply ships as-is and the audit flags it),
 *   - idempotent.
 *
 * Current removals (2026-09-22 content review):
 *   1. Unverifiable player testimonials — four quoted "reviews" attributed to
 *      usernames (MoniK44, V.M, Alakyläboes, Mrkolikkomasiina) with no source,
 *      no date and no way to verify. Fabricated-looking testimonials are a
 *      consumer-protection risk and an E-E-A-T negative on a site recovering
 *      from a quality demotion. The surrounding factual prose stays.
 *   2. A duplicated "Pelitilin vahvistaminen" section — the same ~900
 *      characters appear twice in the fragment (under "Kuinka kasino ilman
 *      rekisteröitymistä toimii?" and again under "Turvallisuus Etusijalla").
 *      The second copy is dropped; the first one keeps its better context.
 */

/** Section heading the testimonials live under. */
const TESTIMONIAL_SECTION_H2 = "Kasinot ilman rekisteröitymistä kokemuksia";

/** The lead-in sentence that introduces the quotes. */
const TESTIMONIAL_LEAD_IN = "kokemuksia pelaajilta";

/** Heading of the DUPLICATE verification section (the second copy). */
const DUPLICATE_VERIFY_H3 = "Pelitilin vahvistaminen kasinolla ilman rekisteröintiä";

/** Heading of the copy we KEEP — the duplicate is only dropped if this exists. */
const KEPT_VERIFY_H3 = "Pelitilin vahvistaminen pikakasinolla";

/**
 * Drop the unverifiable "<strong>Nickname</strong>: <i>“quote”</i>" paragraphs
 * (and the sentence introducing them) from the testimonials section.
 *
 * Scoped to that section only: a <p> elsewhere that happens to pair a <strong>
 * label with an italic phrase is untouched.
 */
export function stripUnverifiedTestimonials(html: string): string {
  if (!html) return "";
  const startRe = new RegExp(`<h2\\b[^>]*>\\s*${TESTIMONIAL_SECTION_H2}\\s*</h2>`, "i");
  const start = startRe.exec(html);
  if (!start) return html;

  const from = start.index + start[0].length;
  const nextH2 = html.slice(from).search(/<h2\b/i);
  const to = nextH2 === -1 ? html.length : from + nextH2;

  const section = html.slice(from, to);
  const cleaned = section
    // The "Tässä muutamia … kokemuksia pelaajilta:" lead-in.
    .replace(
      new RegExp(`<p\\b[^>]*>(?:(?!</p>)[\\s\\S])*?${TESTIMONIAL_LEAD_IN}[\\s\\S]*?</p>`, "gi"),
      "",
    )
    // "<strong>Nickname</strong>: <i>“…”</i>" quote paragraphs.
    .replace(/<p\b[^>]*>(?:(?!<\/p>)[\s\S])*?<strong>(?:(?!<\/p>)[\s\S])*?<i>(?:(?!<\/p>)[\s\S])*?<\/p>/gi, (block) =>
      /[“"”]/.test(block) ? "" : block,
    );

  return html.slice(0, from) + cleaned + html.slice(to);
}

/**
 * Remove the second, verbatim copy of the account-verification section
 * (heading + its paragraphs, up to the next heading). Only runs when the copy
 * we keep is still present, so a future WP rewrite can never delete the topic
 * from the page entirely.
 */
export function stripDuplicateVerificationSection(html: string): string {
  if (!html) return "";
  const keptRe = new RegExp(`<h3\\b[^>]*>\\s*${KEPT_VERIFY_H3}\\s*</h3>`, "i");
  if (!keptRe.test(html)) return html;

  const dupRe = new RegExp(
    `<h3\\b[^>]*>\\s*${DUPLICATE_VERIFY_H3}\\s*</h3>[\\s\\S]*?(?=<h[1-6]\\b|$)`,
    "i",
  );
  return html.replace(dupRe, "");
}

/** All home-prose transforms, in order. Safe to call on an empty string. */
export function cleanHomeProse(html: string): string {
  return stripDuplicateVerificationSection(stripUnverifiedTestimonials(html));
}
