/**
 * home-prose.ts — build-time hygiene for the preserved WordPress home copy.
 *
 * WHY: the home prose is injected VERBATIM from src/fragments/home/body.html
 * (penalty recovery), and that fragment is REGENERATED by the daily WP sync —
 * so hand-editing it is not durable. Anything that must not ship is removed
 * here, at render time, exactly like scrubFirstHandClaims() / ensureSponsored()
 * / stripRetiredBrands() elsewhere in the data layer.
 *
 * Every transform is:
 *   - anchored on stable text in the fragment,
 *   - a NO-OP when its pattern is absent (a WP rewrite can never break the
 *     page — worst case the copy simply ships as-is and the audit flags it),
 *   - idempotent.
 *
 * Current removals (2026-09-22 content review):
 *   1. Unverifiable player testimonials — four quoted "reviews" attributed to
 *      usernames (MoniK44, V.M, Alakyläboes, Mrkolikkomasiina) with no source,
 *      no date and no way to verify. Fabricated-looking testimonials are a
 *      consumer-protection risk and an E-E-A-T negative on a site recovering
 *      from a quality demotion. The surrounding factual prose stays.
 *   2. A duplicated "Pelitilin vahvistaminen" section — the same ~900
 *      characters appear twice in the fragment (under "Kuinka kasino ilman
 *      rekisteröitymistä toimii?" and again under "Turvallisuus Etusijalla").
 *      The second copy is dropped; the first one keeps its better context.
 */

/** Section heading the testimonials live under. */
const TESTIMONIAL_SECTION_H2 = "Kasinot ilman rekisteröitymistä kokemuksia";

/** The lead-in sentence that introduces the quotes. */
const TESTIMONIAL_LEAD_IN = "kokemuksia pelaajilta";

/** Heading of the DUPLICATE verification section (the second copy). */
const DUPLICATE_VERIFY_H3 = "Pelitilin vahvistaminen kasinolla ilman rekisteröintiä";

/** Heading of the copy we KEEP — the duplicate is only dropped if this exists. */
const KEPT_VERIFY_H3 = "Pelitilin vahvistaminen pikakasinolla";

/**
 * Drop the unverifiable "<strong>Nickname</strong>: <i>“quote”</i>" paragraphs
 * (and the sentence introducing them) from the testimonials section.
 *
 * Scoped to that section only: a <p> elsewhere that happens to pair a <strong>
 * label with an italic phrase is untouched.
 */
export function stripUnverifiedTestimonials(html: string): string {
  if (!html) return "";
  const startRe = new RegExp(`<h2\\b[^>]*>\\s*${TESTIMONIAL_SECTION_H2}\\s*</h2>`, "i");
  const start = startRe.exec(html);
  if (!start) return html;

  const from = start.index + start[0].length;
  const nextH2 = html.slice(from).search(/<h2\b/i);
  const to = nextH2 === -1 ? html.length : from + nextH2;

  const section = html.slice(from, to);
  const cleaned = section
    // The "Tässä muutamia … kokemuksia pelaajilta:" lead-in.
    .replace(
      new RegExp(`<p\\b[^>]*>(?:(?!</p>)[\\s\\S])*?${TESTIMONIAL_LEAD_IN}[\\s\\S]*?</p>`, "gi"),
      "",
    )
    // "<strong>Nickname</strong>: <i>“…”</i>" quote paragraphs.
    .replace(/<p\b[^>]*>(?:(?!<\/p>)[\s\S])*?<strong>(?:(?!<\/p>)[\s\S])*?<i>(?:(?!<\/p>)[\s\S])*?<\/p>/gi, (block) =>
      /[“"”]/.test(block) ? "" : block,
    );

  return html.slice(0, from) + cleaned + html.slice(to);
}

/**
 * Remove the second, verbatim copy of the account-verification section
 * (heading + its paragraphs, up to the next heading). Only runs when the copy
 * we keep is still present, so a future WP rewrite can never delete the topic
 * from the page entirely.
 */
export function stripDuplicateVerificationSection(html: string): string {
  if (!html) return "";
  const keptRe = new RegExp(`<h3\\b[^>]*>\\s*${KEPT_VERIFY_H3}\\s*</h3>`, "i");
  if (!keptRe.test(html)) return html;

  const dupRe = new RegExp(
    `<h3\\b[^>]*>\\s*${DUPLICATE_VERIFY_H3}\\s*</h3>[\\s\\S]*?(?=<h[1-6]\\b|$)`,
    "i",
  );
  return html.replace(dupRe, "");
}

/* -------------------------------------------------------------------------- *
 * Redundant <h2> sections (content review 2026-09-22).                         *
 *                                                                              *
 * The home prose ran to ~6,900 words across 24 <h2> sections, several of which  *
 * restate an earlier section in different words — the "wall of near-duplicate   *
 * sections" pattern Google's helpful-content systems treat as filler, on a site *
 * recovering from a quality demotion.                                          *
 *                                                                              *
 * Each entry below is dropped ONLY while its `keeper` section — the one that    *
 * covers the same ground better — is still present, so a future WP rewrite can  *
 * never strip a topic from the page entirely.                                   *
 *                                                                              *
 * Deliberately KEPT even though they are partly repetitive:                     *
 *   - "Uudet nettikasinot…" and "Suomalainen kasino…" carry 9 internal links to *
 *     casino reviews (link equity we want to keep),                             *
 *   - "Kuinka arvioimme…" is the E-E-A-T methodology section,                   *
 *   - the payments / licences / bonuses sections hold the page's unique facts.  *
 * -------------------------------------------------------------------------- */

interface RedundantSection {
  /** <h2> text to remove (normalised comparison: entities decoded, case-insensitive). */
  drop: string;
  /** <h2> that must still exist for the removal to run. */
  keeper: string;
}

const REDUNDANT_SECTIONS: readonly RedundantSection[] = [
  { drop: "Kuinka pelata kasinolla ilman rekisteröintiä", keeper: "Kuinka kasino ilman rekisteröitymistä toimii?" },
  { drop: "Turvallisuus Etusijalla", keeper: "Kasinot ilman rekisteröitymistä – Turvallisuus ja lisenssit" },
  { drop: "Mistä tunnistat kasinot ilman rekisteröitymistä?", keeper: "Kasino ilman rekisteröintiä vs perinteinen nettikasino" },
  { drop: "Pikakasino Kokemus", keeper: "Kasinot ilman rekisteröitymistä kokemuksia" },
  { drop: "Tunnistautuminen ja Dokumentit Pikakasinolla", keeper: "Kuinka kasino ilman rekisteröitymistä toimii?" },
  { drop: "Kuinka nettikasinot ilman rekisteröintiä syntyivät", keeper: "Mikä on kasino ilman rekisteröitymistä?" },
];

/** Heading text → comparable form: tags out, entities decoded, spaces collapsed. */
function headingText(html: string): string {
  return html
    .replace(/<[^>]+>/g, " ")
    .replace(/&#8211;|&ndash;/g, "–")
    .replace(/&#8217;|&rsquo;/g, "’")
    .replace(/&amp;/g, "&")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toLowerCase();
}

/**
 * Drop whole <h2> sections that duplicate a better section elsewhere on the
 * page. Splitting on <h2> boundaries (rather than regex-matching a section) is
 * what makes this safe: a section is removed with exactly its own content, and
 * anything before the first <h2> is always preserved.
 */
export function stripRedundantSections(html: string): string {
  if (!html) return "";
  const parts = html.split(/(?=<h2\b)/i);
  if (parts.length < 2) return html;

  const titleOf = (part: string): string | null => {
    const m = part.match(/<h2[^>]*>([\s\S]*?)<\/h2>/i);
    return m ? headingText(m[1]) : null;
  };
  const present = new Set(parts.map(titleOf).filter(Boolean) as string[]);

  const dropSet = new Set(
    REDUNDANT_SECTIONS.filter((s) => present.has(headingText(s.keeper))).map((s) =>
      headingText(s.drop),
    ),
  );
  if (dropSet.size === 0) return html;

  return parts.filter((p) => { const t = titleOf(p); return !(t && dropSet.has(t)); }).join("");
}

/** All home-prose transforms, in order. Safe to call on an empty string. */
export function cleanHomeProse(html: string): string {
  return stripRedundantSections(
    stripDuplicateVerificationSection(stripUnverifiedTestimonials(html)),
  );
}
