/**
 * html-links.ts — build-time internal-link hygiene for scraped/REST prose.
 *
 * WHY (SEO audit Phases 3 + 4): the crawl found
 *   - a handful of internal links pointing at non-existent URLs (real 404s), and
 *   - ~195 internal links missing the trailing slash that `trailingSlash:
 *     "always"` requires (each one a needless 301 hop that wastes crawl budget
 *     and dilutes link equity on a penalty-recovering domain).
 *
 * Both live INSIDE scraped WordPress prose (data/rest dumps + fragment bodies),
 * which is REGENERATED by the daily WP-sync — so editing the source data is not
 * durable. Instead we fix the links at BUILD TIME on every render, exactly like
 * the existing ensureSponsored() / scrubFirstHandClaims() / optimizeProseImages()
 * passes. The output points DIRECTLY at the final canonical URL (this is link
 * correction, NOT a server redirect — no vercel.json entry is added).
 *
 * Scope: this only ever rewrites the `href` of <a> tags whose target is an
 * INTERNAL PAGE. It NEVER touches:
 *   - affiliate redirects (/go/…), so rel="sponsored nofollow" is untouched,
 *   - assets (.png/.webp/.css/.js/.xml/.json/.svg/.ico/.woff2/…),
 *   - API/system endpoints (/wp-json/, /wp-content/, /feed, WP /embed/),
 *   - external URLs, in-page #hashes, mailto:/tel:/javascript:/data: schemes.
 * Query strings and #fragments are preserved. Idempotent.
 *
 * Systematic broken-link patterns (/blog/…, /new-faq-question…, /casino/<slug>
 * suffix mismatches) are repaired against the REAL route set by
 * resolveInternalPath (src/lib/internal-routes.ts); only renamed-guide one-offs
 * that fit no pattern are hand-mapped in BROKEN_LINK_FIXES below.
 *
 * Build-time (the resolver reads the fragment/casino data layer). The Node audit
 * script scripts/audit-dist-links.mjs re-derives validity from dist/ instead.
 */
import { resolveInternalPath } from "./internal-routes";

/** Bare host of the live site (no scheme). */
const SITE_HOST = "kasinotilmanrekisteroitymista.com";

/**
 * Known-broken internal links → their canonical LIVE target. Keyed by the exact
 * root-relative href as it appears in scraped prose. Each destination is a page
 * verified to exist in the build. This is link CORRECTION (the rendered href is
 * the final URL); it is deliberately a tiny, auditable allowlist, NOT a blanket
 * rewrite. Add an entry only when a specific bad link is confirmed in the crawl.
 *
 * These are the links that fit NO systematic pattern (renamed/typo'd guide slugs
 * and a prefix-less casino link). Each destination is verified to exist in the
 * build. Pattern-based 404s (/blog/…, /new-faq…, /casino/<slug>) are repaired by
 * resolveInternalPath, not here. Keyed by the exact href as authored in prose.
 */
const BROKEN_LINK_FIXES: Readonly<Record<string, string>> = {
  // Pragmatic Play game review — truncated slug + the capitalised variant.
  "/pragmatic-play/john-hunter-and-the-tomb/":
    "/pragmatic-play/john-hunter-and-the-tomb-of-the-scarab-queen/",
  "/pragmatic-play/John-Hunter-and-the-Tomb-of-the-Scarab-Queen/":
    "/pragmatic-play/john-hunter-and-the-tomb-of-the-scarab-queen/",
  // /uutiset/ articles that were never published → most relevant LIVE guide.
  "/uutiset/kierratysvaatimukset-selkokielella/":
    "/kierratysvaatimus-opas-bonusten-kierratykseen/",
  "/uutiset/pikakasinoiden-kotiutusnopeudet-vertailu/":
    "/nopeat-kasino-kotiutusajat-opas-suomalaisille/",
  "/uutiset/mga-lisenssi-vs-viron-lisenssi/": "/mga-kasinot/",
  "/uutiset/verovapaat-kasinovoitot-2026-eta-alueen-lisenssit/":
    "/nain-verovapaus-vaikuttaa-nettikasinopelaamiseen/",
  // Casino review linked without the /casino/ prefix.
  "/ultra-casino": "/casino/ultra-casino/",
  "/ultra-casino/": "/casino/ultra-casino/",
  // Renamed guide slugs (singular→plural / reworded) → current canonical page.
  "/kasino-ilman-rekisteroitymista-ja-vastuullinen-pelaaminen-kuinka-pikakasinot-panostavat-turvallisuuteen":
    "/kasinot-ilman-rekisteroitymista-ja-vastuullinen-pelaaminen-kuinka-pikakasinot-panostavat-turvallisuuteen/",
  "/nettikasinot-ilman-rekisterointia-ja-vastuullinen-pelaaminen":
    "/vastuullinen-pelaaminen-tilittomilla-kasinoilla/",
  "/kasinoiden-bonustarjonnat-minkalaisia-tarjouksia-pikakasinot-tarjoavat":
    "/kasinot-ilman-rekisterointia-ja-bonukset-minkalaisia-tarjouksia-pikakasinot-tarjoavat/",
};

/** File extensions that mark an href as an asset (never a page → never slashed). */
const ASSET_EXT =
  /\.(?:png|jpe?g|webp|avif|gif|svg|ico|css|js|mjs|cjs|json|xml|txt|pdf|zip|csv|woff2?|ttf|eot|mp4|webm|mp3|wav)$/i;

/** Root-relative paths we must not touch (affiliate, API/system, dynamic). */
function isExcludedInternalPath(pathPart: string): boolean {
  if (/^\/go\//i.test(pathPart)) return true; // affiliate redirect
  if (/^\/wp-json\//i.test(pathPart)) return true; // REST API
  if (/^\/wp-content\//i.test(pathPart)) return true; // uploads/assets
  if (/^\/wp-admin\//i.test(pathPart)) return true; // admin
  if (/\/feed\/?$/i.test(pathPart)) return true; // RSS
  if (/\/embed\/?$/i.test(pathPart)) return true; // WP oEmbed endpoint
  if (ASSET_EXT.test(pathPart)) return true; // a file, not a page
  return false;
}

/**
 * Is this href an internal PAGE link (one we may normalise)? Root-relative or
 * same-origin absolute, not an asset/API/affiliate path, not a non-http scheme.
 */
export function isInternalPageHref(href: string): boolean {
  if (!href) return false;
  const t = href.trim();
  if (/^(#|mailto:|tel:|javascript:|data:)/i.test(t)) return false;
  // Strip a same-origin scheme/host to get the path.
  const pathPart = stripSelfOrigin(t).split(/[?#]/)[0];
  // Still has a host → external.
  if (/^(?:https?:)?\/\//i.test(pathPart)) return false;
  if (!pathPart.startsWith("/")) return false;
  return !isExcludedInternalPath(pathPart);
}

/** Remove a leading same-origin scheme+host (or protocol-relative host). */
function stripSelfOrigin(href: string): string {
  return href
    .replace(new RegExp(`^https?://${escapeRe(SITE_HOST)}`, "i"), "")
    .replace(new RegExp(`^//${escapeRe(SITE_HOST)}`, "i"), "");
}

function escapeRe(s: string): string {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Normalise a single href:
 *   1. exact known-broken one-off → canonical live URL,
 *   2. same-origin absolute/protocol-relative → root-relative,
 *   3. internal page path → resolveInternalPath (repairs /blog//new-faq/casino-
 *      slug 404s against the real route set; ensures a trailing slash),
 * preserving any ?query and #hash. External / asset / affiliate / scheme links
 * are returned byte-for-byte unchanged. Idempotent.
 */
export function normalizeInternalHref(href: string): string {
  if (!href) return href;
  const t = href.trim();
  if (/^(#|mailto:|tel:|javascript:|data:)/i.test(t)) return href;

  // 1. Known-broken one-off, as-authored (covers root-relative scraped form).
  if (BROKEN_LINK_FIXES[t]) return BROKEN_LINK_FIXES[t];

  // Split off query/hash to preserve them.
  const cut = t.search(/[?#]/);
  let pathPart = cut === -1 ? t : t.slice(0, cut);
  const suffix = cut === -1 ? "" : t.slice(cut);

  // 2. Same-origin absolute / protocol-relative → root-relative.
  pathPart = stripSelfOrigin(pathPart);

  // Still has a host → external; leave the whole original href untouched.
  if (/^(?:https?:)?\/\//i.test(pathPart)) return href;
  if (!pathPart.startsWith("/")) return href;

  // Known-broken one-off after origin-strip (covers absolute scraped forms).
  if (BROKEN_LINK_FIXES[pathPart]) return BROKEN_LINK_FIXES[pathPart];

  // 3. Excluded internal paths: keep the (possibly relativised) form, no slash.
  if (isExcludedInternalPath(pathPart)) return pathPart + suffix;

  // 4. Internal page → repair to a valid route + ensure trailing slash.
  return resolveInternalPath(pathPart) + suffix;
}

/**
 * Rewrite every <a href="…"> in an HTML prose string via normalizeInternalHref.
 * Double-quoted hrefs only (matches the corpus + ensureSponsored). Tags whose
 * href is unchanged are left byte-identical. Apply AFTER affiliate-rel
 * enforcement; /go/ links are skipped by the normaliser so order is safe.
 */
export function normalizeInternalHtmlLinks(html: string | null | undefined): string {
  if (!html) return "";
  return html.replace(
    /(<a\b[^>]*?\shref=")([^"]*)(")/gi,
    (_whole, pre: string, href: string, post: string) => {
      const fixed = normalizeInternalHref(href);
      return `${pre}${fixed}${post}`;
    },
  );
}
