/**
 * seo-overrides.ts — explicit, auditable per-URL SEO <title>/description/OG
 * overrides for the KIR rebuild.
 *
 * WHY (SEO audit Phase 5): a set of high-impression pages rank but earn ~0
 * clicks because their preserved Rank Math <title>/description do not match the
 * query intent GSC shows (kokemuksia, luotettava, bonus, lisenssi, kotiutus).
 * Rather than edit the scraped fragment heads (regenerated by the WP re-sync,
 * and harder to audit), we keep INTENTIONAL SEO changes in this one typed map,
 * applied over the preserved head at build time (see seo-head.ts).
 *
 * STRICT GUARANTEES (penalty recovery):
 *   - canonical and robots are NEVER touched — only title/description/OG copy.
 *   - NO fabricated freshness. We deliberately do NOT override og:updated_time /
 *     article:modified_time here: a "page updated" signal must reflect a real
 *     content review, which a title/meta-only pass is not (runbook rule 11). Add
 *     a modified-time override only together with an actual body revision.
 *   - NO first-hand / "we tested" claims in any copy below.
 *   - On casino review pages the visible H1 is the casino NAME (rendered
 *     independently of <title>), so a keyword-rich <title> here does not bloat
 *     the H1. On money hubs <title> and H1 share the value, so those titles are
 *     written to read well as a heading too.
 *
 * Keyed by NORMALISED path (single leading + trailing slash) — matches
 * seo-head.ts normalizePath().
 */

/** Intentional SEO override for one URL. Unset fields fall back to the preserved head. */
export interface SeoOverride {
  /** New <title> (also drives og:title/twitter:title unless ogTitle is set). */
  title?: string;
  /** New meta description (also drives og/twitter description unless ogDescription set). */
  description?: string;
  /** Explicit og:title / twitter:title, if it should differ from `title`. */
  ogTitle?: string;
  /** Explicit og:description / twitter:description, if it should differ from `description`. */
  ogDescription?: string;
  /**
   * og:image / twitter:image, ONLY appended when the preserved head has
   * neither already (never replaces an existing image — some fragments do
   * carry a real scraped og:image and that stays untouched). No fabricated
   * imagery: this must be a real, already-hosted site asset.
   */
  ogImage?: string;
}

export const SEO_OVERRIDES: Readonly<Record<string, SeoOverride>> = {
  // --- Casino reviews (H1 = casino name; <title> safe to keyword-optimise) ---
  // Closed 2026-09-15 (closed-casinos.ts). The page is noindexed, but the
  // preserved WP head still called it a "stylish new casino" — say it's closed.
  "/casino/vasy-casino/": {
    title: "Vasy Casino on suljettu – katso avoimet vaihtoehdot",
    description:
      "Vasy Casino on suljettu eikä ota enää vastaan pelaajia. Katso avoimet kasinot ilman rekisteröitymistä.",
  },
  "/casino/igni-casino/": {
    title: "Igni Casino kokemuksia 2026 – bonus, lisenssi ja luotettavuus",
    description:
      "Igni Casino -arvostelu: onko kasino luotettava? Lisenssi, bonusehdot, kotiutusajat, pelivalikoima ja maksutavat suomalaispelaajille 2026.",
  },
  "/casino/casino-vice/": {
    title: "Casino Vice kokemuksia 2026 – bonus, cashback ja kotiutus",
    description:
      "Casino Vice -arvostelu: lisenssi, bonusehdot, cashback, kotiutusajat ja maksutavat. Puolueeton katsaus suomalaispelaajille 2026.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too long" (>60 chars, SERP
  // truncation risk) — title-only, description untouched (not flagged). ---
  "/casino/vegazone/": {
    title: "VegaZone arvostelu 2026 – bonukset ja Zimpler-maksut",
    // description also flagged "too long" (170 chars) in the same audit.
    description:
      "VegaZone arvostelu: bonukset, pelit, maksut, mobiilikäyttö ja turvallisuus. Onko futuristinen VegaZone kokeilemisen arvoinen?",
  },
  "/casino/taika-spinni-kasino/": {
    title: "Taika Spinni arvostelu 2026 – bonukset ja kotiutukset",
    // description also flagged "too long" (166 chars) in the same audit.
    description:
      "Taika Spinni arvostelu: bonukset, pelit, maksut, mobiilikäyttö ja turvallisuus. Onko uusi Taika Spinni kokeilemisen arvoinen?",
  },

  // --- News hub (informational intent; H1 "Uutiset" renders independently) ---
  // GSC (2026-07): the hub ranks pos ~5.7 for "suomalainen nettikasino uutiset"
  // and its child licensing-reform articles rank pos 3-5 ("rahapelit suomi
  // lisenssijärjestelmä 2026"). The preserved title was the generic
  // "Uutiset - <domain>". Aligning the hub with the licensing-reform topic KIR
  // is genuinely winning — informational intent where CTR converts, unlike the
  // brand-navigational review pages. Truthful (the hub aggregates exactly this).
  "/uutiset/": {
    title: "Nettikasinouutiset 2026 – Suomen rahapelit, lisenssit & kasinot",
    description:
      "Tuoreimmat nettikasinouutiset Suomessa: rahapelien lisenssiuudistus 2026, uudet kasinot, bonukset ja alan muutokset. Seuraa KIR-toimituksen uutisointia.",
  },

  // --- Money hubs (<title> and H1 share the value → reads as a heading too) ---
  // GSC (2026-09): the page's own top query is "ilmaiskierrokset ilman
  // talletusta 2022" and it ranks pos ~10-11 for the "2021"-suffixed variants
  // specifically — because the preserved title/description literally say
  // "2021" ("vuodelle 2021"). Meanwhile the real-volume undated query
  // ("ilmaiskierroksia ilman talletusta", 2,293 impressions) sits at pos ~60.
  // Body content (2,391 words) is not date-specific and needs no change —
  // only the 5-year-stale title/description are the problem.
  "/ilmaiskierroksia-ilman-talletusta/": {
    title: "Ilmaiskierroksia ilman talletusta 2026 – täydellinen opas",
    description:
      "Vertaile parhaat ilmaiskierrokset ilman talletusta 2026: ehdot, kierrätysvaatimukset ja luotettavat kasinot suomalaispelaajille.",
  },
  "/nettikasinot-luotettavat-kasinot/": {
    title: "Luotettavat nettikasinot 2026 – vertailu ja kokemukset",
    description:
      "Luotettavat ja turvalliset nettikasinot 2026: lisensoidut kasinot vertailussa. Lue arvostelut, vertaa bonuksia ja kotiutusnopeuksia.",
  },
  "/kryptokasinot/": {
    title: "Kryptokasinot 2026 – parhaat bitcoin- ja kryptokasinot",
    description:
      "Vertaa parhaita kryptokasinoita 2026: bitcoin, USDT ja muut. Nopeat kotiutukset, bonukset, lisenssit ja turvallisuus suomalaispelaajille.",
  },
  "/zimpler-pikakasinot/": {
    title: "Zimpler-pikakasinot 2026 – Pay N Play ja nopeat kotiutukset",
    description:
      "Parhaat Zimpler-pikakasinot 2026: Pay N Play ilman rekisteröitymistä, nopeat kotiutukset ja bonukset. Vertaile ja valitse luotettava kasino.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too long" — informational
  // articles, title-only, description untouched (not flagged). ---
  "/opas-parhaan-kasinobonuksen-loytamiseen/": {
    title: "Opas parhaan kasinobonuksen löytämiseen 2026",
    // description also flagged "too long" (184 chars) in the same audit.
    description:
      "Asiantuntijaopas parhaan kasinobonuksen löytämiseen: non sticky -bonukset 100 % talletuksella ja alhaisella kierrätyksellä.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too short" — generic
  // one/two-word preserved titles carrying no real keyword context. ---
  "/pragmatic-play/": {
    title: "Pragmatic Play kasinopelit 2026 – kolikkopelit ja livekasino",
  },
  "/hacksaw-gaming/": {
    title: "Hacksaw Gaming kasinopelit 2026 – parhaat pelit ja voitot",
  },
  "/ht-faq/": {
    // description was also a placeholder ("FAQs Archive - <domain>") —
    // fixed alongside the title since both were equally uninformative.
    title: "Usein kysytyt kysymykset – Kasinot ilman rekisteröitymistä",
    description:
      "Vastauksia yleisimpiin kysymyksiin kasinoista ilman rekisteröitymistä: rekisteröityminen, talletukset, kotiutukset ja turvallisuus.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Meta description too long"
  // (>~160 chars, SERP truncation risk) — description-only, condensed
  // without dropping any real claim, titles untouched (not flagged). ---
  "/pragmatic-play-pelit-monipuolista-viihdetta/": {
    description:
      "Tutustu Pragmatic Playn pelivalikoimaan: kolikkopelit, livekasino, crash-pelit, bingo ja raaputusarvat. Suosikkeja: Gates of Olympus, Spaceman.",
  },
  "/le-cowboy-arvostelu/": {
    description:
      "Le Cowboy on Hacksaw Gamingin korkean volatiliteetin videoslotti villin lännen teemalla. Lue arvostelu ja katso voittopotentiaali.",
  },
  "/casino/lucky-fruits-casino/": {
    // year tag refreshed 2026-09-15 (was 2025) — see outdated-years block below.
    title: "Lucky Fruits Casino Arvostelu 2026 – 100% Non-sticky Bonus + 100 IK",
    description:
      "Lucky Fruits Casino on Zimpler-pikakasino: 100% non-sticky bonus 300 euroon asti, päivittäinen cashback ja nopeat kotiutukset. Lue arvostelu.",
  },
  "/kimppa-talletukset-nettikasinoilla/": {
    description:
      "Kimppa-talletukset ovat uusi trendi: pelaajat tekevät yhteisiä talletuksia kasinolle. Lue miten ne toimivat sekä hyödyt ja riskit.",
  },
  "/live-blackjack-strategiat/": {
    description:
      "Tutustu parhaisiin live blackjack -strategioihin: perusstrategia ja panostustaktiikat, jotka minimoivat talon edun ja parantavat voittomahdollisuuksia.",
  },
  "/live-game-show-pelit/": {
    description:
      "Tutustu live game show -peleihin: Crazy Time, Monopoly Live ja Sweet Bonanza CandyLand. Opi pelaamaan niitä fiksusti.",
  },
  "/oracle-of-gold-arvostelu/": {
    description:
      "Oracle of Gold on Pragmatic Playn 6x6 cluster-slotti nousevalla globaalikertoimella, joka maksaa parhaimmillaan 10 000x. Lue arvostelu.",
  },
  "/gamification-nettikasinoilla/": {
    description:
      "Mitä gamification eli pelillistäminen nettikasinoilla tarkoittaa? Tutustu tasoihin, tehtäviin ja palkintoihin viihdyttävämmässä pelikokemuksessa.",
  },
  "/pikakasinot/": {
    description:
      "Pikakasinot ovat nopeita kasinoita ilman rekisteröitymistä: tunnistaudu verkkopankilla (Trustly, Zimpler, BRITE) ja kotiuta voitot minuuteissa.",
    // og:image also missing (2026-09-08 audit, "OG tags incomplete") — the
    // scrape never carried one for this page. Reuses the site's existing
    // default social-card asset (same one BaseLayout.astro's net-new-page
    // fallback uses), append-only, never replaces a real image.
    ogImage: "https://kasinotilmanrekisteroitymista.com/og/default.png",
  },
  "/kolikkopelien-eri-rtp-vaihtoehdot/": {
    description:
      "Samalla kolikkopelillä voi olla useita RTP-versioita. Mitä 92%, 94% ja 96% RTP tarkoittavat ja miten teet fiksumpia valintoja?",
  },
  "/parhaat-klassikkoslotit/": {
    // "2025" dropped rather than bumped (2026-09-15): static article prose,
    // not live-updated — a current-year tag would fake freshness.
    title: "Parhaat klassikkoslotit - Tutustu kolikkopeli klassikkoihin",
    description:
      "Esittelyssä kolme parasta klassikkoslottia: Break Da Bank, Emerald Diamond ja Mega Joker. Katso miksi ne ovat yhä pelaajien suosikkeja.",
  },
  "/ilmaiskierrokset-bonukset-ilman/": {
    description:
      "Ilmaiskierrokset ja bonukset ilman talletusta antavat mahdollisuuden testata kasinoita riskittä. Lue miten tarjoukset toimivat.",
  },
  "/kuinka-valita-oikea-kolikkopeli/": {
    description:
      "Etsitkö sopivaa kolikkopeliä? Opas parhaan slotin valintaan RTP:n, volatiliteetin, teeman ja bonusominaisuuksien perusteella.",
  },
  "/yleisimmat-ongelmat-nettikasinoilla-ja-kuinka-ratkaiset-ne/": {
    description:
      "Törmäätkö hitaaseen kotiutukseen tai epäselviin bonusehtoihin? Käymme läpi yleisimmät nettikasino-ongelmat ja niiden ratkaisut.",
  },
  "/mika-tekee-nettikasinopelaamisesta-niin-hauskaa/": {
    description:
      "Nettikasinopelaaminen on muutakin kuin voittojen jahtaamista. Lue mitkä tekijät tekevät pelaamisesta viihdyttävää.",
  },
  "/nettikasino-ilman-rekisteroitymista/": {
    description:
      "Nettikasino ilman rekisteröitymistä tarkoittaa pelaamista verkkopankkitunnuksilla ilman käyttäjätiliä. Vertaa parhaita vaihtoehtoja 2026.",
    // og:image also missing, same "OG tags incomplete" finding — see
    // /pikakasinot/ above for the rationale.
    ogImage: "https://kasinotilmanrekisteroitymista.com/og/default.png",
  },
  "/kolikkopelien-teemat-mika-niissa-viehattaa/": {
    description:
      "Kolikkopelien teemat luovat tunnelman ja houkuttelevat pelaamaan. Katso mitkä teemat toimivat parhaiten ja miksi.",
  },
  "/casino/pelipeto-kasino/": {
    description:
      "Pelipeto Kasino on syksyllä 2025 avattu Zimpler-pikakasino: kierrätysvapaat bonukset, VIP-edut ja verovapaat voitot.",
  },
  "/casino/casinoist/": {
    // 2026-09-15: the earlier "100% tervetulobonus" (lifted from the old
    // scraped title) no longer matched the captured toplist offer.
    title: "Casinoist Kasino arvostelu & kokemuksia 2026",
    description:
      "Casinoist on Pay N Play -kasino: 225 % bonus jopa 1 500 € + 500 ilmaiskierrosta, yli 7000 slottia ja nopeat kotiutukset. Lue arvostelu.",
  },
  "/kolikkopelien-erikoisominaisuudet-mita-kannattaa-tietaa/": {
    description:
      "Kolikkopelien erikoisominaisuudet, kuten laajenevat symbolit ja kertoimet, tuovat jännitystä. Lue miten hyödynnät niitä.",
  },
  "/pragmatic-play-nettikasinopelien-edellakavija/": {
    description:
      "Tutustu Pragmatic Playhin, alan johtavaan pelivalmistajaan: historia, innovatiiviset ominaisuudet ja suosion syyt.",
  },
  "/casino/joki-kasino/": {
    description:
      "Joki Kasino on verovapaa Brite Pay N Play -kasino: 200% talletusbonus 1000 euroon asti. Lue arvostelu bonusehdoista ja peleistä.",
  },
  "/sisarkasinot-vs-itsenaiset-kasinot-kumpi-sopii-sinulle-paremmin/": {
    description:
      "Sisarkasinot vs. itsenäiset kasinot: hyödyt, haitat ja kumpi tarjoaa paremman pelikokemuksen juuri sinulle.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Meta description too short"
  // (<~70 chars, or a broken/placeholder scrape artifact) —
  // description-only, titles untouched (not flagged). 10 of these were the
  // SAME identical templated line across 10 different casinos ("Lue X
  // Kasino arvostelu joka kertoo kasinon bonustiedot, promo koodin, ja
  // pelaajien kokemuksia.") — a duplicate-content problem, not just a
  // length one. Replaced with real per-casino copy, sourced only from
  // facts already published in each page's own <title> (no new claims). ---
  "/kasino-ilman-arvostelut/": {
    // was a broken scrape artifact literally containing a raw URL path
    // ("Kasino Ilman Arvostelut - /kolikkopelien-ostobonukset-hitti-vai-huti/").
    // This is the site's A-Z casino index page.
    description:
      "Aakkosellinen listaus kaikista sivuston kasinoista. Selaa nettikasinot ilman rekisteröitymistä ja siirry suoraan haluamasi kasinon arvosteluun.",
  },
  "/turvalliset-maksutavat-nettikasinoilla-kattava-opas/": {
    description:
      "Mitkä maksutavat ovat turvallisia nettikasinoilla? Kattava opas rahansiirtoihin: Trustly, Zimpler, Brite ja muut suomalaispelaajille.",
  },
  // /parhaat-kasinot-ilman-rekisteroitymista-5/ is Cluster 1's KEEP
  // survivor from the doorway consolidation (docs/doorway-consolidation-map.md)
  // and the site's single best-ranking page (pos ~2.3) — worth a properly
  // crafted description, not just a length patch.
  "/parhaat-kasinot-ilman-rekisteroitymista-5/": {
    description:
      "Vertaile 5 parasta kasinoa ilman rekisteröitymistä 2026: bonukset, nopeat kotiutukset ja luotettavat maksutavat suomalaispelaajille.",
  },
  "/casino/huippukasino/": {
    // year tag refreshed 2026-09-15 (was "(2025)") — see outdated-years block below.
    title: "Huippukasino Arvostelu & Bonustiedot (2026)",
    description:
      "Huippukasino-arvostelu: bonustiedot, pelivalikoima ja pelaajien kokemukset. Lue kattava katsaus ennen rekisteröitymistä.",
  },
  "/casino/reipas/": {
    description:
      "Reipas Kasino on uutuuskasino 500 % tervetulobonuksella. Lue arvostelu bonusehdoista, peleistä ja pelaajien kokemuksista.",
  },
  "/casino/tuohi-kasino/": {
    description:
      "Tuohi Kasino tarjoaa kierrätysvapaita bonuksia. Lue arvostelu bonusehdoista, pelivalikoimasta ja kotiutuksista.",
  },
  "/casino/betizy-kasino/": {
    description:
      "Betizy Kasino -arvostelu: jopa 500 ilmaiskierrosta talletuksella. Bonusehdot, pelivalikoima ja kotiutusajat läpikäytynä.",
  },
  "/casino/rioace/": {
    description:
      "RioAce Kasino -arvostelu: nappaa jopa 1500 euroa bonusta. Lue bonusehdot, pelivalikoima ja pelaajien kokemukset.",
  },
  "/casino/moana-kasino/": {
    // 2026-09-15 CTR batch — see the review-title block at the end of the map.
    title: "Moana Kasino kokemuksia 2026 – 100 % bonus 250 € + 50 IK",
    description:
      "Moana Kasino -arvostelu: 100 % bonus jopa 250 € + 50 ilmaiskierrosta, 35x kierrätys. Kolikkopelit, kotiutus ja pelaajien kokemukset.",
  },
  "/casino/valtti-kasino/": {
    description:
      "Valtti Kasino -arvostelu: nappaa 150 % tervetulobonus. Lue bonusehdot, pelivalikoima ja pelaajien kokemukset.",
  },
  "/casino/klikki-kasino/": {
    description:
      "Klikki Kasino on uusi pikakasino 200 % tervetulobonuksella. Lue arvostelu bonusehdoista ja nopeista kotiutuksista.",
  },
  "/casino/icebet-casino/": {
    description:
      "IceBet Casino -arvostelu: non-sticky bonus jopa 300 euroon asti. Lue bonusehdot, pelivalikoima ja kotiutusajat.",
  },
  "/casino/winz/": {
    description:
      "Winz-kasino tarjoaa yli 5000 peliä. Lue arvostelu bonuksista, RTP-tiedoista ja pelaajien kokemuksista.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Open Graph tags incomplete" —
  // og:image (and consequently twitter:image) missing on all 6 flagged
  // pages; every other OG/Twitter tag was already present and correct.
  // The scrape simply never carried an image for these. All 6 reuse the
  // site's existing default social-card asset — same real, already-hosted
  // PNG BaseLayout.astro's net-new-page fallback uses — append-only via
  // the new `ogImage` override field, never replacing a real image. ---
  "/parhaat-mobiilikasinot-2026-vertailu-ja-valintaopas/": {
    ogImage: "https://kasinotilmanrekisteroitymista.com/og/default.png",
  },
  "/mika-on-tiliton-kasino-ja-miten-se-toimii/": {
    ogImage: "https://kasinotilmanrekisteroitymista.com/og/default.png",
  },

  // --- Outdated years (2026-09-15), casino reviews. Titles like "Arvostelu
  // 2024" were freshness tags that now signal stale content. Review pages
  // render live toplist data (bonus, rating), so the tag should read current
  // — same convention as the Phase-5 "kokemuksia 2026" titles above. Only
  // the year token changes; the rest is the preserved title verbatim (one
  // exception: Fruta's "Upouusi" — "brand new" — dropped, since a 2024
  // casino is not brand new in 2026). Years that state a FACT ("vuonna 2023
  // avattu", launch/founding years) are deliberately left alone everywhere. ---
  "/casino/raketti-kasino/": {
    title: "Raketti Kasino - Arvostelu ja Kokemuksia 2026",
  },
  "/casino/slotti-casino/": {
    title: "Slotti Casino Arvostelu ja Kokemukset 2026",
  },
  "/casino/mammona-kasino/": {
    title: "Mammona Kasino - Arvostelu ja Kokemuksia 2026",
  },
  "/casino/lysti-casino/": {
    title: "Lysti Casino Arvostelu 2026 - 15% Päivittäinen Käteispalautus",
  },
  "/casino/kunkku-kasino/": {
    // 2026-09-15 CTR batch — see the review-title block at the end of the map.
    title: "Kunkku Casino kokemuksia 2026 – 125 % bonus 500 € asti",
    description:
      "Kunkku Kasino (KunkkuKasino) -arvostelu: MGA-kasino, 125 % bonus jopa 500 € + 50 ilmaiskierrosta, 40x kierrätys. Lue kokemukset ja kotiutukset.",
  },
  "/casino/spinit-kasino/": {
    title: "Spinit Kasino - Arvostelu ja Kokemuksia 2026",
  },
  "/casino/kaahaus-kasino/": {
    title: "Kaahaus Kasino Arvostelu 2026 - Kokemuksia ja Bonustiedot",
  },
  "/casino/taikawin-kasino/": {
    title: "Taikawin Kasino Arvostelu 2026 - 15% Käteispalautus!",
  },
  "/casino/fruta-kasino/": {
    title: "Fruta Kasino Arvostelu 2026 | Pikakasino",
  },
  "/casino/netbet-kasino/": {
    title: "NetBet Kasino - Arvostelu 2026",
  },
  "/casino/pelaanyt/": {
    title: "Pelaanyt Kasino Arvostelu & Kokemuksia 2026!",
  },
  "/casino/puzzle-casino/": {
    title: "Puzzle Casino Arvostelu (2026) | 120% bonus 200€ asti!",
  },
  "/casino/rullat/": {
    title: "Rullat Kasino Arvostelu & Kokemuksia 2026",
  },
  "/casino/scarabet-kasino/": {
    title: "Scarabet Kasino Arvostelu 2026 - Ota 200€ Bonus",
  },
  "/casino/slots-hammer-casino/": {
    title: "Slots Hammer Casino Arvostelu (2026) | 120% bonus 200€ asti!",
  },
  "/casino/twin-casino/": {
    // description keeps "avattiin uudelleen vuonna 2023" — a fact, not a tag.
    title: "Twin Casino Arvostelu 2026 | 100% etu 300% asti!",
  },
  "/casino/hurmio-kasino/": {
    // "(2025)" was a bare year tag on the description; removed, not bumped.
    description:
      "Hurmio Kasino on Curacaon lisensoitu pikakasino, Brite Pay N Playllä, minimitalletus 1 €, päivittäinen jopa 15% cashback. Lue arvostelusta lisää!",
  },

  // --- Outdated years (2026-09-15), hubs + static articles. ---
  // Money hubs: <title> doubles as the visible H1 here, so these read as a
  // heading. Both hubs render the live toplist, so the current year is honest.
  "/suomen-parhaat-nettikasinot/": {
    // Shortened from 66 chars (truncated in SERPs) — hub CTR batch 2026-09-15.
    title: "Suomen parhaat nettikasinot 2026 – top kasinot suomalaisille",
    description:
      "Suomen parhaat nettikasinot 2026 vertailussa: lisensoidut MGA- ja Curaçao-kasinot, bonukset, kierrätysehdot ja nopeat kotiutukset.",
  },
  // Was "Uudet kasinot valloittavat Internetin vuonna 2022 | Ei rekisteröintiä";
  // GSC's top query for this page was literally "kasinot 2022".
  "/uudet-kasinot/": {
    title: "Uudet kasinot 2026 – uusimmat kasinot ilman rekisteröintiä",
  },
  // --- Money-hub CTR batch (2026-09-15). GSC 2026-08-15 → 09-15: these hubs
  // get impressions, zero clicks. Titles lead with the exact query wording
  // (e.g. "trustly nettikasinot", "mga lisenssi", "käteispalautus"); <title> is
  // also the visible H1. Year is honest — each hub renders the live toplist.
  // Claims (tax status, no-wagering cashback, Trustly speed) are stated in
  // each page's own body copy. ---
  "/mga-kasinot/": {
    title: "MGA kasinot 2026 – parhaat MGA-lisenssin nettikasinot",
    description:
      "Parhaat MGA-kasinot 2026: Maltan MGA-lisenssi tarkoittaa EU-valvontaa ja verovapaita voittoja suomalaisille. Vertaa bonuksia ja kotiutuksia.",
  },
  "/cashback-kasinot/": {
    title: "Cashback kasinot 2026 – parhaat käteispalautus-bonukset",
    description:
      "Parhaat cashback-kasinot 2026: käteispalautus palauttaa osan tappioista, yleensä ilman kierrätysvaatimusta. Vertaa tarjouksia ilman rekisteröitymistä.",
  },
  // Old title was ungrammatical ("Parhaat trustly nettikasino").
  "/trustly-kasinot/": {
    title: "Trustly nettikasinot 2026 – parhaat Trustly kasinot",
    description:
      "Parhaat Trustly-nettikasinot 2026: talletus ja kotiutus suoraan pankkitililtä, usein muutamassa minuutissa. Vertaa kasinoita, bonuksia ja kotiutuksia.",
  },
  "/curacao-kasinot/": {
    title: "Curacao kasinot 2026 – parhaat Curacao-lisenssin nettikasinot",
    description:
      "Curacao-kasinot 2026: laajat pelivalikoimat ja isot bonukset. Huom: Curacaon lisenssin kasinoilla voitot ovat Suomessa veronalaisia – lue ennen pelaamista.",
  },
  "/apple-pay-casinot/": {
    title: "Apple Pay kasinot 2026 – nettikasinot Apple Pay -talletuksella",
    description:
      "Apple Pay kasinot 2026: talleta iPhonella nopeasti ja turvallisesti, vahvistus Face ID:llä tai sormenjäljellä. Vertaa Apple Pay -nettikasinoita ja bonuksia.",
  },
  // Static articles: year DROPPED rather than bumped — the prose is not
  // live-updated, so claiming 2026 would fake freshness.
  "/parhaat-livekasinopelit-2024/": {
    title: "Parhaat livekasinopelit - Top livepelit",
  },
  "/verovapaus-nettikasinoilla/": {
    description:
      "Nauti pelaamisen tuomasta jännityksestä ja valitse uudet kasinot. Suuntaa verovapaille nettikasinoille ja iloitse voittorahoistasi ilman verottajaa.",
  },

  // --- Review-page CTR batch (2026-09-15). Open reviews ranking ~pos 10-35
  // with real impressions (GSC 2026-08-15 → 09-15) but generic or stale
  // titles. Same formula as the Phase-5 Vasy/Igni titles: brand + the query
  // modifier GSC actually shows ("kokemuksia", "kotiutus") + the CURRENT
  // offer. Every bonus/wagering/license figure is taken from the captured
  // toplist data (public/rlaaf-data) — the same numbers the site's own cards
  // show — never from memory or the old scraped titles, two of which were
  // wrong (Rebellion's "3000€", Casinoist's "100%" above). Brand spelling
  // variants people search ("Jack Burst", "Casino Loots") go in descriptions.
  "/casino/jackburst-casino/": {
    title: "Jackburst Casino kokemuksia 2026 – 100 % bonus 500 € asti",
    description:
      "Jackburst Casino (Jack Burst) -arvostelu: 100 % bonus jopa 500 € + 50 ilmaiskierrosta, 30x kierrätys ja Curaçao-lisenssi. Lue kotiutukset ja pelit.",
  },
  "/casino/kiekka-kasino/": {
    title: "Kiekka Casino kokemuksia 2026 – 20 % cashback & kotiutus",
    description:
      "Kiekka Kasino -arvostelu: 300 ilmaiskierrosta, 20 % päivittäinen cashback, 35x kierrätys ja Curaçao-lisenssi. Lue kotiutusajat ja kokemukset.",
  },
  "/casino/samiland-casino/": {
    title: "Samiland Casino kokemuksia 2026 – 300 % bonus 1000 € asti",
    description:
      "Samiland Casino -arvostelu: 300 % tervetulobonus jopa 1000 €, 30x kierrätys ja Curaçao-lisenssi. Lue bonusehdot, pelit ja kotiutukset.",
  },
  "/casino/slotsi-kasino/": {
    title: "Slotsi Casino kokemuksia 2026 – 125 % bonus 500 € asti",
    description:
      "Slotsi Kasino -arvostelu: White Hat Gamingin MGA-pikakasino, 125 % bonus jopa 500 € (40x kierrätys). Kolikkopelit, kotiutukset ja kokemukset.",
  },
  "/casino/kaleo-casino/": {
    // description already specific; title swaps generic "bonukset, pelit ja
    // kotiutukset" for the concrete offer (ranks pos ~12-13).
    title: "Kaleo Casino arvostelu 2026 – 100 % bonus 250 € + 50 IK",
  },
  "/casino/casinoloots/": {
    // description was truncated mid-sentence ("Lue Casinoloots arvostelu, kokemuksia,").
    title: "Casinoloots kokemuksia 2026 – 100 % bonus 250 € + 50 IK",
    description:
      "Casinoloots (Casino Loots) on Trumo-pikakasino suomalaisille: 100 % bonus jopa 250 € + 50 ilmaiskierrosta, 30x kierrätys. Lue arvostelu ja kokemukset.",
  },
  "/casino/mr-fortune-casino/": {
    // was a generic slogan ("Avaa polkusi kasinomenestykseen").
    title: "Mr Fortune kokemuksia 2026 – 100 % bonus 700 € & kotiutus",
    description:
      "Mr Fortune Kasino -arvostelu: MGA-lisensoitu kasino, 100 % bonus jopa 700 € + 50 ilmaiskierrosta (40x kierrätys). Lue kotiutusajat ja kokemukset.",
  },
  "/casino/trada-casino/": {
    // "trada casino kotiutus" already ranks pos ~4 — lead with it.
    title: "Trada Casino kokemuksia 2026 – kotiutus, bonus ja 150 IK",
    description:
      "Trada Casino -arvostelu: MGA-lisensoitu kasino, 100 % bonus jopa 100 € + 150 ilmaiskierrosta. Lue kotiutusajat, kolikkopelit ja kokemukset.",
  },
  "/casino/spinnair/": {
    // was the bare scraped "Spinnair - kasinotilmanrekisteroitymista.com".
    title: "Spinnair Kasino arvostelu 2026 – 200 IK & 20 % cashback",
  },
  "/casino/rebellion-casino/": {
    // old title promised "Jopa 3000€ Bonus"; the current offer is 1000 €.
    title: "Rebellion Casino kokemuksia 2026 – bonus 1000 € + 100 IK",
  },
  "/casino/slottimonsteri-kasino/": {
    title: "SlottiMonsteri Casino kokemuksia 2026 – bonus 500 € + 100 IK",
    description:
      "SlottiMonsteri Kasino -arvostelu: 100 % bonus jopa 500 € + 100 ilmaiskierrosta, 35x kierrätys ja Curaçao-lisenssi. Lue kotiutus ja kokemukset.",
  },
};

/* -------------------------------------------------------------------------- */
/* Application                                                                 */
/* -------------------------------------------------------------------------- */

import type { SeoHead } from "./seo-head";

/** Minimal attribute escaper for reconstructed/edited meta content. */
function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

/**
 * Replace the content="…" of a raw <meta> tag string (either attribute order).
 * Delimiter-aware: matches the ACTUAL quote char used, so a literal apostrophe
 * inside a double-quoted value can't truncate the replacement and splice
 * leftover old text after the new value.
 */
function replaceMetaContent(tag: string, value: string): string {
  if (/\bcontent\s*=\s*"/i.test(tag)) {
    return tag.replace(/(\bcontent\s*=\s*")[^"]*(")/i, `$1${escapeAttr(value)}$2`);
  }
  if (/\bcontent\s*=\s*'/i.test(tag)) {
    return tag.replace(
      /(\bcontent\s*=\s*')[^']*(')/i,
      `$1${escapeAttr(value).replace(/'/g, "&#39;")}$2`,
    );
  }
  // No content attr (defensive) — inject one before the tag closes.
  return tag.replace(/\s*\/?>\s*$/, ` content="${escapeAttr(value)}" />`);
}

type OgKind = "ogTitle" | "ogDesc" | "twTitle" | "twDesc" | null;
function ogKind(tag: string): OgKind {
  if (/\bproperty=["']og:title["']/i.test(tag)) return "ogTitle";
  if (/\bproperty=["']og:description["']/i.test(tag)) return "ogDesc";
  if (/\bname=["']twitter:title["']/i.test(tag)) return "twTitle";
  if (/\bname=["']twitter:description["']/i.test(tag)) return "twDesc";
  return null;
}

/**
 * Apply the SEO_OVERRIDES entry for `normalizedPath` (if any) over a parsed
 * SeoHead. Returns the same object reference when there is no override.
 * canonical / robots / jsonLd are passed through untouched.
 */
export function applySeoOverride(normalizedPath: string, seo: SeoHead): SeoHead {
  const ov = SEO_OVERRIDES[normalizedPath];
  if (!ov) return seo;

  const title = ov.title ?? seo.title;
  const description = ov.description ?? seo.description;
  const ogTitle = ov.ogTitle ?? ov.title ?? null;
  const ogDescription = ov.ogDescription ?? ov.description ?? null;

  let sawOgTitle = false;
  let sawOgDesc = false;
  const ogTags = seo.ogTags.map((tag) => {
    const kind = ogKind(tag);
    if (kind === "ogTitle" && ogTitle != null) {
      sawOgTitle = true;
      return replaceMetaContent(tag, ogTitle);
    }
    if (kind === "ogDesc" && ogDescription != null) {
      sawOgDesc = true;
      return replaceMetaContent(tag, ogDescription);
    }
    if (kind === "twTitle" && ogTitle != null) return replaceMetaContent(tag, ogTitle);
    if (kind === "twDesc" && ogDescription != null) return replaceMetaContent(tag, ogDescription);
    return tag;
  });

  // Append og:title / og:description only if the source head lacked them, so the
  // social card stays consistent with the overridden <title>/description.
  if (ogTitle != null && !sawOgTitle) {
    ogTags.push(`<meta property="og:title" content="${escapeAttr(ogTitle)}" />`);
  }
  if (ogDescription != null && !sawOgDesc) {
    ogTags.push(`<meta property="og:description" content="${escapeAttr(ogDescription)}" />`);
  }

  // og:image / twitter:image — append-only, never replace a real scraped image.
  if (ov.ogImage != null) {
    const hasOgImage = ogTags.some((t) => /\bproperty=["']og:image["']/i.test(t));
    const hasTwImage = ogTags.some((t) => /\bname=["']twitter:image["']/i.test(t));
    if (!hasOgImage) {
      ogTags.push(`<meta property="og:image" content="${escapeAttr(ov.ogImage)}" />`);
    }
    if (!hasTwImage) {
      ogTags.push(`<meta name="twitter:image" content="${escapeAttr(ov.ogImage)}" />`);
    }
  }

  return { ...seo, title, description, ogTags };
}
