/**
 * seo-overrides.ts — explicit, auditable per-URL SEO <title>/description/OG
 * overrides for the KIR rebuild.
 *
 * WHY (SEO audit Phase 5): a set of high-impression pages rank but earn ~0
 * clicks because their preserved Rank Math <title>/description do not match the
 * query intent GSC shows (kokemuksia, luotettava, bonus, lisenssi, kotiutus).
 * Rather than edit the scraped fragment heads (regenerated by the WP re-sync,
 * and harder to audit), we keep INTENTIONAL SEO changes in this one typed map,
 * applied over the preserved head at build time (see seo-head.ts).
 *
 * STRICT GUARANTEES (penalty recovery):
 *   - canonical and robots are NEVER touched — only title/description/OG copy.
 *   - NO fabricated freshness. We deliberately do NOT override og:updated_time /
 *     article:modified_time here: a "page updated" signal must reflect a real
 *     content review, which a title/meta-only pass is not (runbook rule 11). Add
 *     a modified-time override only together with an actual body revision.
 *   - NO first-hand / "we tested" claims in any copy below.
 *   - On casino review pages the visible H1 is the casino NAME (rendered
 *     independently of <title>), so a keyword-rich <title> here does not bloat
 *     the H1. On money hubs <title> and H1 share the value, so those titles are
 *     written to read well as a heading too.
 *
 * Keyed by NORMALISED path (single leading + trailing slash) — matches
 * seo-head.ts normalizePath().
 */

/** Intentional SEO override for one URL. Unset fields fall back to the preserved head. */
export interface SeoOverride {
  /** New <title> (also drives og:title/twitter:title unless ogTitle is set). */
  title?: string;
  /** New meta description (also drives og/twitter description unless ogDescription set). */
  description?: string;
  /** Explicit og:title / twitter:title, if it should differ from `title`. */
  ogTitle?: string;
  /** Explicit og:description / twitter:description, if it should differ from `description`. */
  ogDescription?: string;
}

export const SEO_OVERRIDES: Readonly<Record<string, SeoOverride>> = {
  // --- Casino reviews (H1 = casino name; <title> safe to keyword-optimise) ---
  "/casino/vasy-casino/": {
    title: "Vasy Casino kokemuksia 2026 – bonus, lisenssi ja kotiutus",
    description:
      "Vasy Casino -arvostelu: lisenssi, bonusehdot, kierrätys, kotiutusajat ja maksutavat. Puolueeton katsaus suomalaispelaajille 2026.",
  },
  "/casino/igni-casino/": {
    title: "Igni Casino kokemuksia 2026 – bonus, lisenssi ja luotettavuus",
    description:
      "Igni Casino -arvostelu: onko kasino luotettava? Lisenssi, bonusehdot, kotiutusajat, pelivalikoima ja maksutavat suomalaispelaajille 2026.",
  },
  "/casino/casino-vice/": {
    title: "Casino Vice kokemuksia 2026 – bonus, cashback ja kotiutus",
    description:
      "Casino Vice -arvostelu: lisenssi, bonusehdot, cashback, kotiutusajat ja maksutavat. Puolueeton katsaus suomalaispelaajille 2026.",
  },

  // --- Money hubs (<title> and H1 share the value → reads as a heading too) ---
  "/nettikasinot-luotettavat-kasinot/": {
    title: "Luotettavat nettikasinot 2026 – vertailu ja kokemukset",
    description:
      "Luotettavat ja turvalliset nettikasinot 2026: lisensoidut kasinot vertailussa. Lue arvostelut, vertaa bonuksia ja kotiutusnopeuksia.",
  },
  "/kryptokasinot/": {
    title: "Kryptokasinot 2026 – parhaat bitcoin- ja kryptokasinot",
    description:
      "Vertaa parhaita kryptokasinoita 2026: bitcoin, USDT ja muut. Nopeat kotiutukset, bonukset, lisenssit ja turvallisuus suomalaispelaajille.",
  },
  "/zimpler-pikakasinot/": {
    title: "Zimpler-pikakasinot 2026 – Pay N Play ja nopeat kotiutukset",
    description:
      "Parhaat Zimpler-pikakasinot 2026: Pay N Play ilman rekisteröitymistä, nopeat kotiutukset ja bonukset. Vertaile ja valitse luotettava kasino.",
  },
};

/* -------------------------------------------------------------------------- */
/* Application                                                                 */
/* -------------------------------------------------------------------------- */

import type { SeoHead } from "./seo-head";

/** Minimal attribute escaper for reconstructed/edited meta content. */
function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

/** Replace the content="…" of a raw <meta> tag string (either attribute order). */
function replaceMetaContent(tag: string, value: string): string {
  if (/\bcontent=["']/i.test(tag)) {
    return tag.replace(/(\bcontent=["'])[^"']*(["'])/i, `$1${escapeAttr(value)}$2`);
  }
  // No content attr (defensive) — inject one before the tag closes.
  return tag.replace(/\s*\/?>\s*$/, ` content="${escapeAttr(value)}" />`);
}

type OgKind = "ogTitle" | "ogDesc" | "twTitle" | "twDesc" | null;
function ogKind(tag: string): OgKind {
  if (/\bproperty=["']og:title["']/i.test(tag)) return "ogTitle";
  if (/\bproperty=["']og:description["']/i.test(tag)) return "ogDesc";
  if (/\bname=["']twitter:title["']/i.test(tag)) return "twTitle";
  if (/\bname=["']twitter:description["']/i.test(tag)) return "twDesc";
  return null;
}

/**
 * Apply the SEO_OVERRIDES entry for `normalizedPath` (if any) over a parsed
 * SeoHead. Returns the same object reference when there is no override.
 * canonical / robots / jsonLd are passed through untouched.
 */
export function applySeoOverride(normalizedPath: string, seo: SeoHead): SeoHead {
  const ov = SEO_OVERRIDES[normalizedPath];
  if (!ov) return seo;

  const title = ov.title ?? seo.title;
  const description = ov.description ?? seo.description;
  const ogTitle = ov.ogTitle ?? ov.title ?? null;
  const ogDescription = ov.ogDescription ?? ov.description ?? null;

  let sawOgTitle = false;
  let sawOgDesc = false;
  const ogTags = seo.ogTags.map((tag) => {
    const kind = ogKind(tag);
    if (kind === "ogTitle" && ogTitle != null) {
      sawOgTitle = true;
      return replaceMetaContent(tag, ogTitle);
    }
    if (kind === "ogDesc" && ogDescription != null) {
      sawOgDesc = true;
      return replaceMetaContent(tag, ogDescription);
    }
    if (kind === "twTitle" && ogTitle != null) return replaceMetaContent(tag, ogTitle);
    if (kind === "twDesc" && ogDescription != null) return replaceMetaContent(tag, ogDescription);
    return tag;
  });

  // Append og:title / og:description only if the source head lacked them, so the
  // social card stays consistent with the overridden <title>/description.
  if (ogTitle != null && !sawOgTitle) {
    ogTags.push(`<meta property="og:title" content="${escapeAttr(ogTitle)}" />`);
  }
  if (ogDescription != null && !sawOgDesc) {
    ogTags.push(`<meta property="og:description" content="${escapeAttr(ogDescription)}" />`);
  }

  return { ...seo, title, description, ogTags };
}
