/**
 * seo-overrides.ts — explicit, auditable per-URL SEO <title>/description/OG
 * overrides for the KIR rebuild.
 *
 * WHY (SEO audit Phase 5): a set of high-impression pages rank but earn ~0
 * clicks because their preserved Rank Math <title>/description do not match the
 * query intent GSC shows (kokemuksia, luotettava, bonus, lisenssi, kotiutus).
 * Rather than edit the scraped fragment heads (regenerated by the WP re-sync,
 * and harder to audit), we keep INTENTIONAL SEO changes in this one typed map,
 * applied over the preserved head at build time (see seo-head.ts).
 *
 * STRICT GUARANTEES (penalty recovery):
 *   - canonical and robots are NEVER touched — only title/description/OG copy.
 *   - NO fabricated freshness. We deliberately do NOT override og:updated_time /
 *     article:modified_time here: a "page updated" signal must reflect a real
 *     content review, which a title/meta-only pass is not (runbook rule 11). Add
 *     a modified-time override only together with an actual body revision.
 *   - NO first-hand / "we tested" claims in any copy below.
 *   - On casino review pages the visible H1 is the casino NAME (rendered
 *     independently of <title>), so a keyword-rich <title> here does not bloat
 *     the H1. On money hubs <title> and H1 share the value, so those titles are
 *     written to read well as a heading too.
 *
 * Keyed by NORMALISED path (single leading + trailing slash) — matches
 * seo-head.ts normalizePath().
 */

/** Intentional SEO override for one URL. Unset fields fall back to the preserved head. */
export interface SeoOverride {
  /** New <title> (also drives og:title/twitter:title unless ogTitle is set). */
  title?: string;
  /** New meta description (also drives og/twitter description unless ogDescription set). */
  description?: string;
  /** Explicit og:title / twitter:title, if it should differ from `title`. */
  ogTitle?: string;
  /** Explicit og:description / twitter:description, if it should differ from `description`. */
  ogDescription?: string;
}

export const SEO_OVERRIDES: Readonly<Record<string, SeoOverride>> = {
  // --- Casino reviews (H1 = casino name; <title> safe to keyword-optimise) ---
  "/casino/vasy-casino/": {
    title: "Vasy Casino kokemuksia 2026 – bonus, lisenssi ja kotiutus",
    description:
      "Vasy Casino -arvostelu: lisenssi, bonusehdot, kierrätys, kotiutusajat ja maksutavat. Puolueeton katsaus suomalaispelaajille 2026.",
  },
  "/casino/igni-casino/": {
    title: "Igni Casino kokemuksia 2026 – bonus, lisenssi ja luotettavuus",
    description:
      "Igni Casino -arvostelu: onko kasino luotettava? Lisenssi, bonusehdot, kotiutusajat, pelivalikoima ja maksutavat suomalaispelaajille 2026.",
  },
  "/casino/casino-vice/": {
    title: "Casino Vice kokemuksia 2026 – bonus, cashback ja kotiutus",
    description:
      "Casino Vice -arvostelu: lisenssi, bonusehdot, cashback, kotiutusajat ja maksutavat. Puolueeton katsaus suomalaispelaajille 2026.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too long" (>60 chars, SERP
  // truncation risk) — title-only, description untouched (not flagged). ---
  "/casino/vegazone/": {
    title: "VegaZone arvostelu 2026 – bonukset ja Zimpler-maksut",
    // description also flagged "too long" (170 chars) in the same audit.
    description:
      "VegaZone arvostelu: bonukset, pelit, maksut, mobiilikäyttö ja turvallisuus. Onko futuristinen VegaZone kokeilemisen arvoinen?",
  },
  "/casino/taika-spinni-kasino/": {
    title: "Taika Spinni arvostelu 2026 – bonukset ja kotiutukset",
    // description also flagged "too long" (166 chars) in the same audit.
    description:
      "Taika Spinni arvostelu: bonukset, pelit, maksut, mobiilikäyttö ja turvallisuus. Onko uusi Taika Spinni kokeilemisen arvoinen?",
  },

  // --- News hub (informational intent; H1 "Uutiset" renders independently) ---
  // GSC (2026-07): the hub ranks pos ~5.7 for "suomalainen nettikasino uutiset"
  // and its child licensing-reform articles rank pos 3-5 ("rahapelit suomi
  // lisenssijärjestelmä 2026"). The preserved title was the generic
  // "Uutiset - <domain>". Aligning the hub with the licensing-reform topic KIR
  // is genuinely winning — informational intent where CTR converts, unlike the
  // brand-navigational review pages. Truthful (the hub aggregates exactly this).
  "/uutiset/": {
    title: "Nettikasinouutiset 2026 – Suomen rahapelit, lisenssit & kasinot",
    description:
      "Tuoreimmat nettikasinouutiset Suomessa: rahapelien lisenssiuudistus 2026, uudet kasinot, bonukset ja alan muutokset. Seuraa KIR-toimituksen uutisointia.",
  },

  // --- Money hubs (<title> and H1 share the value → reads as a heading too) ---
  // GSC (2026-09): the page's own top query is "ilmaiskierrokset ilman
  // talletusta 2022" and it ranks pos ~10-11 for the "2021"-suffixed variants
  // specifically — because the preserved title/description literally say
  // "2021" ("vuodelle 2021"). Meanwhile the real-volume undated query
  // ("ilmaiskierroksia ilman talletusta", 2,293 impressions) sits at pos ~60.
  // Body content (2,391 words) is not date-specific and needs no change —
  // only the 5-year-stale title/description are the problem.
  "/ilmaiskierroksia-ilman-talletusta/": {
    title: "Ilmaiskierroksia ilman talletusta 2026 – täydellinen opas",
    description:
      "Vertaile parhaat ilmaiskierrokset ilman talletusta 2026: ehdot, kierrätysvaatimukset ja luotettavat kasinot suomalaispelaajille.",
  },
  "/nettikasinot-luotettavat-kasinot/": {
    title: "Luotettavat nettikasinot 2026 – vertailu ja kokemukset",
    description:
      "Luotettavat ja turvalliset nettikasinot 2026: lisensoidut kasinot vertailussa. Lue arvostelut, vertaa bonuksia ja kotiutusnopeuksia.",
  },
  "/kryptokasinot/": {
    title: "Kryptokasinot 2026 – parhaat bitcoin- ja kryptokasinot",
    description:
      "Vertaa parhaita kryptokasinoita 2026: bitcoin, USDT ja muut. Nopeat kotiutukset, bonukset, lisenssit ja turvallisuus suomalaispelaajille.",
  },
  "/zimpler-pikakasinot/": {
    title: "Zimpler-pikakasinot 2026 – Pay N Play ja nopeat kotiutukset",
    description:
      "Parhaat Zimpler-pikakasinot 2026: Pay N Play ilman rekisteröitymistä, nopeat kotiutukset ja bonukset. Vertaile ja valitse luotettava kasino.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too long" — informational
  // articles, title-only, description untouched (not flagged). ---
  "/tilittomien-kasinoiden-turvallisuusvaatimukset/": {
    title: "Tilittömien kasinoiden turvallisuusvaatimukset 2026",
  },
  "/kasinoiden-lisenssivaatimukset-turvallisuus-ja-pelivalinta/": {
    title: "Kasinoiden lisenssivaatimukset 2026 – turvallisuusopas",
  },
  "/opas-parhaan-kasinobonuksen-loytamiseen/": {
    title: "Opas parhaan kasinobonuksen löytämiseen 2026",
    // description also flagged "too long" (184 chars) in the same audit.
    description:
      "Asiantuntijaopas parhaan kasinobonuksen löytämiseen: non sticky -bonukset 100 % talletuksella ja alhaisella kierrätyksellä.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Title too short" — generic
  // one/two-word preserved titles carrying no real keyword context. ---
  "/pragmatic-play/": {
    title: "Pragmatic Play kasinopelit 2026 – kolikkopelit ja livekasino",
  },
  "/hacksaw-gaming/": {
    title: "Hacksaw Gaming kasinopelit 2026 – parhaat pelit ja voitot",
  },
  "/ht-faq/": {
    // description was also a placeholder ("FAQs Archive - <domain>") —
    // fixed alongside the title since both were equally uninformative.
    title: "Usein kysytyt kysymykset – Kasinot ilman rekisteröitymistä",
    description:
      "Vastauksia yleisimpiin kysymyksiin kasinoista ilman rekisteröitymistä: rekisteröityminen, talletukset, kotiutukset ja turvallisuus.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Meta description too long"
  // (>~160 chars, SERP truncation risk) — description-only, condensed
  // without dropping any real claim, titles untouched (not flagged). ---
  "/pragmatic-play-pelit-monipuolista-viihdetta/": {
    description:
      "Tutustu Pragmatic Playn pelivalikoimaan: kolikkopelit, livekasino, crash-pelit, bingo ja raaputusarvat. Suosikkeja: Gates of Olympus, Spaceman.",
  },
  "/le-cowboy-arvostelu/": {
    description:
      "Le Cowboy on Hacksaw Gamingin korkean volatiliteetin videoslotti villin lännen teemalla. Lue arvostelu ja katso voittopotentiaali.",
  },
  "/casino/lucky-fruits-casino/": {
    description:
      "Lucky Fruits Casino on Zimpler-pikakasino: 100% non-sticky bonus 300 euroon asti, päivittäinen cashback ja nopeat kotiutukset. Lue arvostelu.",
  },
  "/kimppa-talletukset-nettikasinoilla/": {
    description:
      "Kimppa-talletukset ovat uusi trendi: pelaajat tekevät yhteisiä talletuksia kasinolle. Lue miten ne toimivat sekä hyödyt ja riskit.",
  },
  "/live-blackjack-strategiat/": {
    description:
      "Tutustu parhaisiin live blackjack -strategioihin: perusstrategia ja panostustaktiikat, jotka minimoivat talon edun ja parantavat voittomahdollisuuksia.",
  },
  "/live-game-show-pelit/": {
    description:
      "Tutustu live game show -peleihin: Crazy Time, Monopoly Live ja Sweet Bonanza CandyLand. Opi pelaamaan niitä fiksusti.",
  },
  "/oracle-of-gold-arvostelu/": {
    description:
      "Oracle of Gold on Pragmatic Playn 6x6 cluster-slotti nousevalla globaalikertoimella, joka maksaa parhaimmillaan 10 000x. Lue arvostelu.",
  },
  "/gamification-nettikasinoilla/": {
    description:
      "Mitä gamification eli pelillistäminen nettikasinoilla tarkoittaa? Tutustu tasoihin, tehtäviin ja palkintoihin viihdyttävämmässä pelikokemuksessa.",
  },
  "/pikakasinot/": {
    description:
      "Pikakasinot ovat nopeita kasinoita ilman rekisteröitymistä: tunnistaudu verkkopankilla (Trustly, Zimpler, BRITE) ja kotiuta voitot minuuteissa.",
  },
  "/kolikkopelien-eri-rtp-vaihtoehdot/": {
    description:
      "Samalla kolikkopelillä voi olla useita RTP-versioita. Mitä 92%, 94% ja 96% RTP tarkoittavat ja miten teet fiksumpia valintoja?",
  },
  "/parhaat-klassikkoslotit/": {
    description:
      "Esittelyssä kolme parasta klassikkoslottia: Break Da Bank, Emerald Diamond ja Mega Joker. Katso miksi ne ovat yhä pelaajien suosikkeja.",
  },
  "/ilmaiskierrokset-bonukset-ilman/": {
    description:
      "Ilmaiskierrokset ja bonukset ilman talletusta antavat mahdollisuuden testata kasinoita riskittä. Lue miten tarjoukset toimivat.",
  },
  "/kuinka-valita-oikea-kolikkopeli/": {
    description:
      "Etsitkö sopivaa kolikkopeliä? Opas parhaan slotin valintaan RTP:n, volatiliteetin, teeman ja bonusominaisuuksien perusteella.",
  },
  "/yleisimmat-ongelmat-nettikasinoilla-ja-kuinka-ratkaiset-ne/": {
    description:
      "Törmäätkö hitaaseen kotiutukseen tai epäselviin bonusehtoihin? Käymme läpi yleisimmät nettikasino-ongelmat ja niiden ratkaisut.",
  },
  "/miten-pikakasinot-toimivat-nopea-ja-turvallinen-opas-2026/": {
    description:
      "Opi miten pikakasinot toimivat ilman rekisteröitymistä: verkkopankkitunnistautuminen, turvallisuus ja nopeat rahansiirrot 2026.",
  },
  "/mika-tekee-nettikasinopelaamisesta-niin-hauskaa/": {
    description:
      "Nettikasinopelaaminen on muutakin kuin voittojen jahtaamista. Lue mitkä tekijät tekevät pelaamisesta viihdyttävää.",
  },
  "/nettikasino-ilman-rekisteroitymista/": {
    description:
      "Nettikasino ilman rekisteröitymistä tarkoittaa pelaamista verkkopankkitunnuksilla ilman käyttäjätiliä. Vertaa parhaita vaihtoehtoja 2026.",
  },
  "/maksutapojen-merkitys-tilittomilla-kasinoilla-valitse/": {
    description:
      "Opi valitsemaan paras maksutapa tilittömälle kasinolle. Vertailu: Trustly, Zimpler ja muut — nopeus, turvallisuus ja käytännön vinkit.",
  },
  "/casino/berriez-casino/": {
    description:
      "Berriez Casino on suomalaisille suunnattu pikakasino: välittömät kotiutukset, päivittäinen cashback ja matalat kierrätysvaatimukset.",
  },
  "/kolikkopelien-teemat-mika-niissa-viehattaa/": {
    description:
      "Kolikkopelien teemat luovat tunnelman ja houkuttelevat pelaamaan. Katso mitkä teemat toimivat parhaiten ja miksi.",
  },
  "/casino/pelipeto-kasino/": {
    description:
      "Pelipeto Kasino on syksyllä 2025 avattu Zimpler-pikakasino: kierrätysvapaat bonukset, VIP-edut ja verovapaat voitot.",
  },
  "/casino/casinoist/": {
    description:
      "Casinoist on uusi Pay N Play -kasino: 100% tervetulobonus, yli 7000 slottia ja nopeat kotiutukset. Lue arvostelu.",
  },
  "/kolikkopelien-erikoisominaisuudet-mita-kannattaa-tietaa/": {
    description:
      "Kolikkopelien erikoisominaisuudet, kuten laajenevat symbolit ja kertoimet, tuovat jännitystä. Lue miten hyödynnät niitä.",
  },
  "/pragmatic-play-nettikasinopelien-edellakavija/": {
    description:
      "Tutustu Pragmatic Playhin, alan johtavaan pelivalmistajaan: historia, innovatiiviset ominaisuudet ja suosion syyt.",
  },
  "/casino/joki-kasino/": {
    description:
      "Joki Kasino on verovapaa Brite Pay N Play -kasino: 200% talletusbonus 1000 euroon asti. Lue arvostelu bonusehdoista ja peleistä.",
  },
  "/kasinot-ilman-rekisteroitymista-2026-70-turvallisempia-pelaajia/": {
    description:
      "Kasinot ilman rekisteröitymistä 2026: 70% turvallisempia pankkitunnistuksella, nopeat kotiutukset ja selkeät bonukset.",
  },
  "/casino/speedz-casino/": {
    description:
      "Speedz Casino on Trumo-pikakasino: yli 4000 peliä, nopeat kotiutukset ja 300 ilmaiskierrosta alkuun. Lue arvostelu.",
  },
  "/vastuullinen-pelaaminen-tilittomilla-kasinoilla/": {
    description:
      "Opi vastuullisen pelaamisen periaatteet tilittömillä kasinoilla: self-exclusion-työkalut ja impulsiivisuuden hallinta.",
  },
  "/casino/flamez-kasino/": {
    description:
      "Flamez Kasino on uusi TrumoPay-pikakasino: 200 ilmaiskierroksen tervetuliaisbonus, 20% cashback ja yli 5400 peliä.",
  },
  "/miksi-valita-kasino-ilman-rekisteroitymista/": {
    description:
      "Miksi valita kasino ilman rekisteröitymistä 2026: tärkeimmät edut, maksutavat, bonukset ja turvallisuus suomalaispelaajille.",
  },
  "/sisarkasinot-vs-itsenaiset-kasinot-kumpi-sopii-sinulle-paremmin/": {
    description:
      "Sisarkasinot vs. itsenäiset kasinot: hyödyt, haitat ja kumpi tarjoaa paremman pelikokemuksen juuri sinulle.",
  },
  "/turvallisen-tilittoman-kasinon-valinta-2026/": {
    description:
      "Opi valitsemaan turvallinen tilitön kasino 2026: tarkista lisenssit ja maksutavat, vältä yleisimmät virheet.",
  },

  // --- Ahrefs Site Audit (2026-09-08), "Meta description too short"
  // (<~70 chars, or a broken/placeholder scrape artifact) —
  // description-only, titles untouched (not flagged). 10 of these were the
  // SAME identical templated line across 10 different casinos ("Lue X
  // Kasino arvostelu joka kertoo kasinon bonustiedot, promo koodin, ja
  // pelaajien kokemuksia.") — a duplicate-content problem, not just a
  // length one. Replaced with real per-casino copy, sourced only from
  // facts already published in each page's own <title> (no new claims). ---
  "/kasino-ilman-arvostelut/": {
    // was a broken scrape artifact literally containing a raw URL path
    // ("Kasino Ilman Arvostelut - /kolikkopelien-ostobonukset-hitti-vai-huti/").
    // This is the site's A-Z casino index page.
    description:
      "Aakkosellinen listaus kaikista sivuston kasinoista. Selaa nettikasinot ilman rekisteröitymistä ja siirry suoraan haluamasi kasinon arvosteluun.",
  },
  "/turvalliset-maksutavat-nettikasinoilla-kattava-opas/": {
    description:
      "Mitkä maksutavat ovat turvallisia nettikasinoilla? Kattava opas rahansiirtoihin: Trustly, Zimpler, Brite ja muut suomalaispelaajille.",
  },
  // /parhaat-kasinot-ilman-rekisteroitymista-5/ is Cluster 1's KEEP
  // survivor from the doorway consolidation (docs/doorway-consolidation-map.md)
  // and the site's single best-ranking page (pos ~2.3) — worth a properly
  // crafted description, not just a length patch.
  "/parhaat-kasinot-ilman-rekisteroitymista-5/": {
    description:
      "Vertaile 5 parasta kasinoa ilman rekisteröitymistä 2026: bonukset, nopeat kotiutukset ja luotettavat maksutavat suomalaispelaajille.",
  },
  "/casino/huippukasino/": {
    description:
      "Huippukasino-arvostelu: bonustiedot, pelivalikoima ja pelaajien kokemukset. Lue kattava katsaus ennen rekisteröitymistä.",
  },
  "/casino/reipas/": {
    description:
      "Reipas Kasino on uutuuskasino 500 % tervetulobonuksella. Lue arvostelu bonusehdoista, peleistä ja pelaajien kokemuksista.",
  },
  "/casino/pelikioski/": {
    description:
      "Pelikioski Kasino -arvostelu: bonukset, pelivalikoima, maksutavat ja asiakaspalvelu. Kattava katsaus suomalaispelaajille.",
  },
  "/casino/tuohi-kasino/": {
    description:
      "Tuohi Kasino tarjoaa kierrätysvapaita bonuksia. Lue arvostelu bonusehdoista, pelivalikoimasta ja kotiutuksista.",
  },
  "/casino/betizy-kasino/": {
    description:
      "Betizy Kasino -arvostelu: jopa 500 ilmaiskierrosta talletuksella. Bonusehdot, pelivalikoima ja kotiutusajat läpikäytynä.",
  },
  "/casino/rioace/": {
    description:
      "RioAce Kasino -arvostelu: nappaa jopa 1500 euroa bonusta. Lue bonusehdot, pelivalikoima ja pelaajien kokemukset.",
  },
  "/casino/moana-kasino/": {
    description:
      "Moana Kasino tarjoaa kolme talletusbonusta uusille pelaajille. Lue arvostelu bonusehdoista, peleistä ja kotiutuksista.",
  },
  "/casino/valtti-kasino/": {
    description:
      "Valtti Kasino -arvostelu: nappaa 150 % tervetulobonus. Lue bonusehdot, pelivalikoima ja pelaajien kokemukset.",
  },
  "/casino/klikki-kasino/": {
    description:
      "Klikki Kasino on uusi pikakasino 200 % tervetulobonuksella. Lue arvostelu bonusehdoista ja nopeista kotiutuksista.",
  },
  "/casino/icebet-casino/": {
    description:
      "IceBet Casino -arvostelu: non-sticky bonus jopa 300 euroon asti. Lue bonusehdot, pelivalikoima ja kotiutusajat.",
  },
  "/casino/winz/": {
    description:
      "Winz-kasino tarjoaa yli 5000 peliä. Lue arvostelu bonuksista, RTP-tiedoista ja pelaajien kokemuksista.",
  },
};

/* -------------------------------------------------------------------------- */
/* Application                                                                 */
/* -------------------------------------------------------------------------- */

import type { SeoHead } from "./seo-head";

/** Minimal attribute escaper for reconstructed/edited meta content. */
function escapeAttr(s: string): string {
  return s.replace(/&/g, "&amp;").replace(/"/g, "&quot;").replace(/</g, "&lt;");
}

/**
 * Replace the content="…" of a raw <meta> tag string (either attribute order).
 * Delimiter-aware: matches the ACTUAL quote char used, so a literal apostrophe
 * inside a double-quoted value can't truncate the replacement and splice
 * leftover old text after the new value.
 */
function replaceMetaContent(tag: string, value: string): string {
  if (/\bcontent\s*=\s*"/i.test(tag)) {
    return tag.replace(/(\bcontent\s*=\s*")[^"]*(")/i, `$1${escapeAttr(value)}$2`);
  }
  if (/\bcontent\s*=\s*'/i.test(tag)) {
    return tag.replace(
      /(\bcontent\s*=\s*')[^']*(')/i,
      `$1${escapeAttr(value).replace(/'/g, "&#39;")}$2`,
    );
  }
  // No content attr (defensive) — inject one before the tag closes.
  return tag.replace(/\s*\/?>\s*$/, ` content="${escapeAttr(value)}" />`);
}

type OgKind = "ogTitle" | "ogDesc" | "twTitle" | "twDesc" | null;
function ogKind(tag: string): OgKind {
  if (/\bproperty=["']og:title["']/i.test(tag)) return "ogTitle";
  if (/\bproperty=["']og:description["']/i.test(tag)) return "ogDesc";
  if (/\bname=["']twitter:title["']/i.test(tag)) return "twTitle";
  if (/\bname=["']twitter:description["']/i.test(tag)) return "twDesc";
  return null;
}

/**
 * Apply the SEO_OVERRIDES entry for `normalizedPath` (if any) over a parsed
 * SeoHead. Returns the same object reference when there is no override.
 * canonical / robots / jsonLd are passed through untouched.
 */
export function applySeoOverride(normalizedPath: string, seo: SeoHead): SeoHead {
  const ov = SEO_OVERRIDES[normalizedPath];
  if (!ov) return seo;

  const title = ov.title ?? seo.title;
  const description = ov.description ?? seo.description;
  const ogTitle = ov.ogTitle ?? ov.title ?? null;
  const ogDescription = ov.ogDescription ?? ov.description ?? null;

  let sawOgTitle = false;
  let sawOgDesc = false;
  const ogTags = seo.ogTags.map((tag) => {
    const kind = ogKind(tag);
    if (kind === "ogTitle" && ogTitle != null) {
      sawOgTitle = true;
      return replaceMetaContent(tag, ogTitle);
    }
    if (kind === "ogDesc" && ogDescription != null) {
      sawOgDesc = true;
      return replaceMetaContent(tag, ogDescription);
    }
    if (kind === "twTitle" && ogTitle != null) return replaceMetaContent(tag, ogTitle);
    if (kind === "twDesc" && ogDescription != null) return replaceMetaContent(tag, ogDescription);
    return tag;
  });

  // Append og:title / og:description only if the source head lacked them, so the
  // social card stays consistent with the overridden <title>/description.
  if (ogTitle != null && !sawOgTitle) {
    ogTags.push(`<meta property="og:title" content="${escapeAttr(ogTitle)}" />`);
  }
  if (ogDescription != null && !sawOgDesc) {
    ogTags.push(`<meta property="og:description" content="${escapeAttr(ogDescription)}" />`);
  }

  return { ...seo, title, description, ogTags };
}
