/**
 * middleware.ts — Vercel Edge Middleware for /go/<slug>/ affiliate redirects.
 *
 * WHY (2026-08-10): these used to be static rules in vercel.json's
 * `redirects` array. Vercel hard-caps that array at 1024 entries; this site
 * crossed it (1110 rules, 964 of them /go/), which silently 404'd 86 real
 * affiliate links in production with zero build-time warning — Vercel just
 * drops anything past rule #1024, no error, no log. Middleware has no such
 * ceiling: the lookup table is just bundled data, checked at request time.
 *
 * Data source: data/go-redirects.json, a flat { slug: destinationUrl } map
 * regenerated by scripts/fetch-rest.mjs on every WP sync (merged with
 * data/go-redirects-manual.json for slugs not yet in ThirstyAffiliates).
 *
 * Matches both /go/<slug> and /go/<slug>/ (vercel.json's trailingSlash:true
 * normalizes bare paths to the slashed form before middleware runs, but the
 * lookup strips it either way so both forms work regardless of that order).
 * Unknown slugs fall through (no return value) so Vercel serves its normal
 * static 404 — never invents a destination.
 */
import redirects from "./data/go-redirects.json";

export const config = {
  matcher: "/go/:slug*",
};

const REDIRECTS: Record<string, string> = redirects;

export default function middleware(request: Request): Response | undefined {
  const url = new URL(request.url);
  const match = /^\/go\/([^/]+)\/?$/i.exec(url.pathname);
  if (!match) return undefined;

  const slug = decodeURIComponent(match[1]).toLowerCase();
  const destination = REDIRECTS[slug];
  if (!destination) return undefined;

  return Response.redirect(destination, 307);
}
